---
title: "Homer Theme"
subtitle: "Walkx"
logo: "logo.png"

header: false
footer: '<p>Theme made with <span class="has-text-danger">❤️</span> by <a href="https://github.com/WalkxCode">Walkx</a></p>' # Set false if you want to hide it.

stylesheet:
  - "assets/custom.css"

columns: "3" # You can change this to any number that is a factor of 12: (1, 2, 3, 4, 6, 12)
theme: default
colors:
  light:
    highlight-primary: "#fff5f2"
    highlight-secondary: "#fff5f2"
    highlight-hover: "#bebebe"
    background: "#12152B"
    card-background: "rgba(255, 245, 242, 0.8)"
    text: "#ffffff"
    text-header: "#fafafa"
    text-title: "#000000"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#2e4053"
    background-image: "../assets/wallpaper-light.jpeg" # Change wallpaper.jpeg to the name of your own custom wallpaper!
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "rgba(24, 28, 58, 0.8)"
    text: "#eaeaea"
    text-header: "#7C71DD"
    text-title: "#fafafa"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#c1c1c1"
    link-hover: "#fafafa"
    background-image: "../assets/wallpaper.jpeg"

services:
  - name: "// TV En vivo"
    # icon: "fas fa-github"
    items:
      - name: "TV Pública"
        logo: "https://tvpublica.com.ar/favicon.ico" # Change github.png to the name of your own custom icon!
        url: "https://tvpublica.com.ar"
        target: "live"
      - name: "PlutoTV"
        logo: "assets/icons/pluto.png"
        url: "https://pluto.tv/"
        target: "live"

  - name: "// Streaming"
    # icon: "fas fa-reddit"
    items:
      - name: "Netflix"
        logo: "https://netflix.com/favicon.ico"
        url: "https://netflix.com/"
        target: "streaming"
      - name: "Crunchyroll"
        logo: "assets/icons/crunchyroll.jpg"
        url: "https://crunchyroll.com/"
        target: "streaming"
      - name: "Disney+"
        logo: "https://www.disneyplus.com/favicon.ico"
        url: "https://disneyplus.com/"
        target: "streaming"
      - name: "Star+"
        logo: "https://www.starplus.com/favicon.ico"
        url: "https://www.starplus.com/"
        target: "streaming"
